# Generated by Django 5.2.7 on 2025-10-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
