# Generated by Django 5.2.7 on 2025-10-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_App', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ToDo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
