# Generated by Django 5.2.7 on 2025-10-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_App', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
    ]
