# Generated by Django 5.2.7 on 2025-10-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_App', '0006_remove_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
