# Generated by Django 5.2.7 on 2025-10-03 03:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_App', '0007_user_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='todo',
            name='time_spent',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
