# Generated by Django 5.2.7 on 2025-10-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_Do_App', '0008_remove_todo_end_time_alter_todo_time_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('paused', 'Paused'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
